flags: {}
packages:
- '.'
- lib/theory/
- lib/term/
- lib/utils/
- lib/sapic/
- lib/export/
- lib/accountability/
resolver: lts-22.44
ghc-options:
  "$everything": -Wall
extra-lib-dirs:
- lib/fvpgenbib
nix:
  packages: [ zlib ]

